version: '2'
services:
  simpleservice:
      image: johncarnell/tmx-simple-service:chapter1
      ports:
        - "8080"
  nginx:
      image: nginx:latest
      volumes:
         - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
          - simpleservice
      ports:
          - "4000:4000"